"""Added salon table and relationship with alumno

Revision ID: abe8c022b15b
Revises: 998f109c32ee
Create Date: 2023-04-11 15:49:17.211090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe8c022b15b'
down_revision = '998f109c32ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aula', sa.String(length=20), nullable=True),
    sa.Column('horaEntrada', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'salon', ['idAula'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('salon')
    # ### end Alembic commands ###
